openapi: "3.0.2"

info:
  title: State Backed API
  description: |
    The official State Backed API for running XState backends as a service.

    State Backed turns any XState state machine into a stateful backend.
    Spawn instances of your machines, authorize requests,
    send events, and read your instances' state without any servers
    or datastores to manage.

    View the full State Backed documentation at https://docs.statebacked.dev.

    Download the `smply` CLI at https://npmjs.com/package/smply
    or at https://github.com/state-backed/smply/releases.
  version: 1.0.0

servers:
  - url: https://api.statebacked.dev
    description: Production server

x-topics:
  - title: Authentication
    content: |
      # End-user JWT authentication

      Pass the JWT token in the `Authorization` header as `Bearer <token>`.

      ## Use

      State Backed authenticates requests to ensure that they include a valid JWT
      signed by one of your StateBacked keys.

      State Backed also passes the user data from the `act` claim of your JWT to your
      machine's `allowRead` and `allowWrite` functions to allow you to authorize operations
      on machine instances.

      ## Generation

      Use the key (`sbk_...`) and secret (`sbsec_...`) generated from running `smply keys create`
      to sign a JWT token with an `act` claim that includes data about your end user
      (e.g. a `sub` claim with the user's ID).

      ```
      HS256("sbsec_...", { "kid": "sbk_...", "alg": "HS256" }, { "aud": "https://api.statebacked.dev/", "act": { "sub": "..." }, ... })
      ```

      You can also use our token generation library:
      ```
      import { signToken } from "@statebacked/token";

      const jwt = await signToken({
        {
          stateBackedKeyId: process.env.STATEBACKED_KEY_ID,
          stateBackedSecretKey: process.env.STATEBACKED_SECRET_KEY
        },
        {
          sub: "your-user-id"
        },
        {
          expires: { in: "7d" },
          issuer: "https://your-domain.com/"
        }
      });
      ```

tags:
  - name: Machines
    description: |
      # Machine definition operations.

      Machine definitions name a logical machine from which you can create
      multiple *machine instances*.

      Machine definitions have multiple *machine definition versions*, one
      of which is named as the current version.
  - name: Machine versions
    description: |
      # Machine definition version operations.

      Machine definition versions contain the actual machine definition,
      which consists of a single self-contained javascript file that
      default exports an [XState](https://xstate.js.org/docs/) state
      machine as well as an `allowRead` and `allowWrite` function.

      The `allowRead` and `allowWrite` functions are called to authorize
      read and write operations on machine instances, respectively.
      Write authorization implies the authority to read the result of
      your write.

      Anything stored in the machine's context under the `public` key
      will be exposed to authorized readers and writers as `publicContext`.

      ## Example machine definition

      ```js
      import type {
        AllowRead,
        AllowWrite
      } from "@statebacked/machine-def";
      import { createMachine } from "xstate";

      export const allowRead: AllowRead = (
        { machineInstanceName, authContext },
      ) => machineInstanceName === authContext.sub;

      export const allowWrite: AllowWrite = (
        { machineInstanceName, authContext },
      ) => machineInstanceName === authContext.sub;

      export default createMachine(...);
      ```
  - name: Machine version migrations
    description: |
      # Machine version migration operations.

      Machine version migrations are small snippets of code that migrate
      existing machine instances from one machine version to another.
      They consist of a single self-contained javascript file that
      exports `upgradeState` and `upgradeContext` functions.

      ## Example machine version migration

      ```js
      import type {
        UpgradeState,
        UpgradeContext
      } from "@statebacked/machine-def";

      export const upgradeState: UpgradeState = (oldState, oldContext) => {
        // oldState is an array describing a full path to a state in the old version of the machine
        // (e.g. ["authenticationPage", "login"] if login is a child state of authenticationPage).
        // oldContext is the most recent context of the machine. It *may not* be a valid context in
        // the given state because upgradeState will be called to migrate history states in
        // addition to current states.

        // a simple renaming of a parent state from "authenticationPage" to "newAuthenticationPage".
        return oldState[0] === "authenticationPage" ? ["newAuthenticationPage"].concat(oldState.slice(1)) : oldState;
      };

      export const upgradeContext: UpgradeContext = (oldStates, newStates, oldContext) => {
        // oldStates is an array of state paths from the old version of the machine.
        // (e.g. [["a", "b"], ["a", "c"]] if "a" is a parallel state and is in both "b" and "c").
        // newStates is an array of state paths from the new version of the machine.
        // oldContext is the context associated with oldStates in the old version of the machine.

        return {
          ...oldContext,
          upgradeCount: oldContext.upgradeCount + 1
        };
      };
      ```
  - name: Machine instances
    description: |
      # Machine instance operations.
      
      Machine instances are instances of a machine definition.

      If you have a machine definition that controls a user onboarding flow,
      you would want a machine instance for each user.

      If you have a machine definition that controls access to a collaborative
      document, you would want a machine instance for each document.

      Machine instances have names that are unique within a machine definition.

      You can send events to machine instances to trigger transitions and can
      read the state of an instance.

      ## Consistency guarantees

      Processing for a machine instance is coordinated such that there is
      a single, linearizable history of events and state transitions.

      ## Limits

      Machine context (represented as JSON) may not exceed 400kb.
  - name: Logs
    description: |
      # Logs produced while processing transitions and migrations.

      State Backed collects any logs you emit while processing
      transitions and migrations and makes them available via this
      endpoint.

      State Backed also emits some logs of its own to provide context.

      We *highly* recommend logging structured JSON objects.
  - name: Realtime
    description: |
      # Realtime (websocket) endpoints

      State Backed allows you to subscribe to machine instance updates
      via websockets.

paths:
  /machines:
    summary: Machine definition operations.
    description: |
      Machine definitions name a logical machine from which you can create
      multiple *machine instances*.

      Machine definitions have multiple *machine definition versions*, one
      of which is named as the current version.
    post:
      summary: Create a new machine definition.
      tags:
        - Machines
      security:
        - BearerAuth:
          - "machines.write"
      description: |
        Note: No instances of a machine definition can be created until
        you create a machine definition version for it.
  /machines/{machineSlug}:
    post:
      tags:
        - Machine instances
      summary: Create a new machine instance.
      description: |
        Create a new instance of the machine definition with the given slug.

        The `allowWrite` function for the machine definition version will be called
        to authorize the initial transition and, if it fails, a 403 with code
        `rejected-by-machine-authorizer` will be returned.

        Otherwise, the state of the machine instance after the initial transition
        will be returned.

        All top-level events have a 10 second timeout for the machine to settle.
        Settling means that the machine has reached a stable state and has no
        child services running.

        If the machine does not settle within 10 seconds but has completed at least
        one transition successfully, a 200 with the current state will be returned,
        the child services will be stopped, and error events will be delivered for
        each stopped service before the next event is sent.

        If a machine instance for this (`machineSlug`, instance `slug`) already exists,
        a 409 will be returned.
      security:
        - BearerAuth:
          - "instances.write"
    delete:
      tags:
        - Machines
      summary: Delete a machine and any versions and migrations associated with it.
      description: |
        Delete a machine and any versions and migrations associated with it.

        *THIS IS OBVIOUSLY A DANGEROUS OPERATION AND WILL INTENTIONALLY CAUSE DATA LOSS*

        If any instances exist for the machine, a 409 error will be returned with an `invalid-state` code.
        You can delete the instances and then retry the machine deletion.

        All versions associated with the machine and all migrations between those versions
        will be deleted.
        
        There is no option to recover data after a machine is deleted.

        To prevent accidental deletion, we require two validation parameters:
          - hmacSha256OfMachineNameWithMachineNameKey - `base64urlEncode(hmacSha256(key = "machine name", "machine name"))`
          - dangerDataWillBeDeletedForever - true

        A 400 error with the `parameter` set to the name of the incorrect parameter will be returned
        if the validation parameters are incorrect.

        This endpoint requires admin access.
      security:
        - BearerAuth:
          - "machines.admin"
  /machines/{machineSlug}/i/{instanceSlug}:
    get:
      tags:
        - Machine instances
      summary: Get the current state of a machine instance.
      description: |
        Retrieve the state of the machine instance that was previously created by
        calling `POST /machines/{machineSlug}` and may have had events sent to it
        by calling `POST /machines/{machineSlug}/i/{instanceSlug}/events`.

        The `allowRead` function for the machine definition version will be called
        to authorize the read and, if it fails, a 403 with code
        `rejected-by-machine-authorizer` will be returned.

        Otherwise, the current state of the machine instance will be returned.

        Obviously, the state returned may be out of date by the time it is returned
        because reads are non-blocking but a the returned state will always be
        self-consistent.
      security:
        - BearerAuth:
          - "instances.read"
    delete:
      tags:
        - Machine instances
      summary: Delete a machine instance and any transitions, state, or pending upgrades associated with it.
      description: |
        Delete a machine instance and any transitions, state, or pending upgrades associated with it.

        *THIS IS OBVIOUSLY A DANGEROUS OPERATION AND WILL INTENTIONALLY CAUSE DATA LOSS*

        All historical transitions associated with the machine and all current state and context
        will be deleted.
        
        There is no option to recover data after an instance is deleted.

        To prevent accidental deletion, we require two validation parameters:
          - hmacSha256OfMachineInstanceNameWithMachineNameKey - `base64urlEncode(hmacSha256(key = "machine name", "machine instance name"))`
          - dangerDataWillBeDeletedForever - true

        A 400 error with the `parameter` set to the name of the incorrect parameter will be returned
        if the validation parameters are incorrect.

        This endpoint requires admin access.
      security:
        - BearerAuth:
          - "instances.admin"
  /machines/{machineSlug}/i/{instanceSlug}/events:
    post:
      tags:
        - Machine instances
      summary: Send an event to a machine instance.
      description: |
        Send an event to the machine instance that was previously created by
        calling `POST /machines/{machineSlug}`.

        The `allowWrite` function for the machine definition version will be called
        to authorize the send and, if it fails, a 403 with code
        `rejected-by-machine-authorizer` will be returned.

        Otherwise, the state of the machine instance after any transitions resulting
        from the event will be returned.

        The request will wait for the machine to settle before returning a response.
        Settling means that the machine has reached a stable state and has no
        child services running.

        All top-level events have a 10 second timeout for the machine to settle.

        If the machine does not settle within 10 seconds but has completed at least
        one transition successfully, a 200 with the current state will be returned,
        the child services will be stopped, and error events will be delivered for
        each stopped service before the next event is sent.
      security:
        - BearerAuth:
          - "instances.write"
  /machines/{machineSlug}/i/{instanceSlug}/v:
    put:
      tags:
        - Machine instances
      summary: Update the desired machine version for an existing instance.
      description: |
        Set the desired machine version for an existing instance.

        The instance will not be upgraded immediately but will be upgraded
        the next time an event is sent to it from a settled state.

        A 400 with code "no-migration-path" will be returned if there is
        no path through the set of existing migrations from the current
        instance version to the desired instance version.
      security:
        - BearerAuth:
          - "instances.write"
  /machines/{machineSlug}/i/{instanceSlug}/status:
    put:
      tags:
        - Machine instances
      summary: Update the status of a machine instance
      description: |
        Set the status of the machine.

        Machines in the 'paused' status will reject any events sent to them
        with a 409 error with a code of "invalid-state".

        'running' instances will accept events normally.

        It is **dangerous** to set an instance's status to 'paused'!
        You will drop events and, because delayed events are only retried
        5 times (with ~30 seconds between each try), some delayed events
        may be dropped and **never** sent to your machine.

        This exists **purely** to stop a runaway machine instance that is
        stuck in a loop of creating too many events.

        This endpoint requires admin access.
      security:
        - BearerAuth:
          - "instances.admin"
  /machines/{machineSlug}/v:
    summary: Machine definition version operations.
    description: |
      Machine definition versions are comprised of an XState machine,
      an `allowRead` function, and an `allowWrite` function.

      They are immutable and identified by an ID.
      The `clientInfo` field is informational only.
    post:
      tags:
        - Machine versions
      summary: Provisionally create a new machine definition version.
      description: |
        This operation returns a code upload URL and fields that can be used
        to upload the code for the machine definition version.

        Once the code is uploaded, call `PUT /machines/:machineSlug/v/:machineDefinitionVersionId`
        with the `machineDefinitionVersionId` returned from this operation to
        finalize the creation of the machine definition version.
      security:
        - BearerAuth:
          - "machine-versions.write"
  /machines/{machineSlug}/v/{signedMachineVersionId}:
    put:
      tags:
        - Machine versions
      summary: Finalize creation of a machine definition version.
      description: |
        After retrieving the `machineDefinitionVersionId` and code upload
        instructions from `POST /machines/:machineSlug/v`, and after
        uploading the code as described, call this operation to finalize
        the creation of the machine definition version.

        After this operation, you can create instances of the machine
        definition with  this version.
      security:
        - BearerAuth:
          - "machine-versions.write"
  /machines/{machineSlug}/migrations:
    post:
      tags:
        - Machine version migrations
      summary: Provisionally create a new machine version migration.
      description: |
        This operation returns a code upload URL and fields that can be used
        to upload the code for the machine version migration.

        Once the code is uploaded, call `PUT /machines/:machineSlug/migrations/:machineVersionMigrationId`
        with the `machineVersionMigrationId` returned from this operation to
        finalize the creation of the machine version migration.
      security:
        - BearerAuth:
          - "machine-versions.write"
  /machines/{machineSlug}/migrations/{signedMachineVersionMigrationId}:
    put:
      tags:
        - Machine version migrations
      summary: Finalize creation of a machine version migration.
      description: |
        After retrieving the `machineVersionMigrationId` and code upload
        instructions from `POST /machines/:machineSlug/migrations`, and after
        uploading the code as described, call this operation to finalize
        the creation of the machine version migration.

        After this operation, you can upgrade existing machine instances
        using this migration.
      security:
        - BearerAuth:
          - "machine-versions.write"
  /logs:
    get:
      tags:
        - Logs
      summary: Retrieve logs for a time range.
      description: |
        Retrieve logs starting at the `from` time, optionally
        filtered by `to`, `machine`, `instance`, and `version`.

        You will receive at most 100 log entries (each consisting
        of potentially multiple lines) but you may receive fewer
        entries due to various partitioning schemes.

        You may retry the call by specifying the returned `maxTimestamp`
        as the new `from` time to retrieve additional logs.
      security:
        - BearerAuth:
          - "logs.read"
  /rt:
    get:
      tags:
        - Realtime
      summary: Subscribe to real-time updates of machine instances.
      description: |
        This is a websocket endpoint.
        Connect and send WSToServerMsg messages and receive WSToClientMsg messages.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
