openapi: "3.0.2"

info:
  title: State Backed API
  description: |
    The official State Backed API for running XState backends as a service.

    State Backed turns any XState state machine into a stateful backend.
    Spawn instances of your machines, authorize requests,
    send events, and read your instances' state without any servers
    or datastores to manage.

    View the full State Backed documentation at https://docs.statebacked.dev.

    Download the `smply` CLI at https://npmjs.com/package/smply
    or at https://github.com/state-backed/smply/releases.
  version: 1.0.0

servers:
  - url: https://api.statebacked.dev
    description: Production server

x-topics:
  - title: Authentication
    content: |
      # End-user JWT authentication

      Pass the JWT token in the `Authorization` header as `Bearer <token>`.

      ## Use

      State Backed authenticates requests to ensure that they include a valid JWT
      signed by one of your StateBacked keys.

      State Backed also passes the user data from the `act` claim of your JWT to your
      machine's `allowRead` and `allowWrite` functions to allow you to authorize operations
      on machine instances.

      ## Generation

      Use the key (`sbk_...`) and secret (`sbsec_...`) generated from running `smply keys create`
      to sign a JWT token with an `act` claim that includes data about your end user
      (e.g. a `sub` claim with the user's ID).

      ```
      HS256("sbsec_...", { "kid": "sbk_...", "alg": "HS256" }, { "aud": "https://api.statebacked.dev/", "act": { "sub": "..." }, ... })
      ```

      You can also use our token generation library:
      ```
      import { signToken } from "@statebacked/token";

      const jwt = await signToken({
        {
          stateBackedKeyId: process.env.STATEBACKED_KEY_ID,
          stateBackedSecretKey: process.env.STATEBACKED_SECRET_KEY
        },
        {
          sub: "your-user-id"
        },
        {
          expires: { in: "7d" },
          issuer: "https://your-domain.com/"
        }
      });
      ```

tags:
  - name: Machines
    description: |
      # Machine definition operations.

      Machine definitions name a logical machine from which you can create
      multiple *machine instances*.

      Machine definitions have multiple *machine definition versions*, one
      of which is named as the current version.
  - name: Machine versions
    description: |
      # Machine definition version operations.

      Machine definition versions contain the actual machine definition,
      which consists of a single self-contained javascript file that
      default exports an [XState](https://xstate.js.org/docs/) state
      machine as well as an `allowRead` and `allowWrite` function.

      They are immutable and identified by an ID.
      The `clientInfo` field is informational only and intended to be used to
      identify the source of the machine version (e.g. git commit sha,
      semantic version number, timestamp, etc).

      The `allowRead` and `allowWrite` functions are called to authorize
      read and write operations on machine instances, respectively.
      Write authorization implies the authority to read the result of
      your write.

      Anything stored in the machine's context under the `public` key
      will be exposed to authorized readers and writers as `publicContext`.

      ## Example machine definition

      ```js
      import type {
        AllowRead,
        AllowWrite
      } from "@statebacked/machine-def";
      import { createMachine } from "xstate";

      export const allowRead: AllowRead = (
        { machineInstanceName, authContext },
      ) => machineInstanceName === authContext.sub;

      export const allowWrite: AllowWrite = (
        { machineInstanceName, authContext },
      ) => machineInstanceName === authContext.sub;

      export default createMachine(...);
      ```
  - name: Machine version migrations
    description: |
      # Machine version migration operations.

      Machine version migrations are small snippets of code that migrate
      existing machine instances from one machine version to another.
      They consist of a single self-contained javascript file that
      exports `upgradeState` and `upgradeContext` functions.

      ## Example machine version migration

      ```js
      import type {
        UpgradeState,
        UpgradeContext
      } from "@statebacked/machine-def";

      export const upgradeState: UpgradeState = (oldState, oldContext) => {
        // oldState is an array describing a full path to a state in the old version of the machine
        // (e.g. ["authenticationPage", "login"] if login is a child state of authenticationPage).
        // oldContext is the most recent context of the machine. It *may not* be a valid context in
        // the given state because upgradeState will be called to migrate history states in
        // addition to current states.

        // a simple renaming of a parent state from "authenticationPage" to "newAuthenticationPage".
        return oldState[0] === "authenticationPage" ? ["newAuthenticationPage"].concat(oldState.slice(1)) : oldState;
      };

      export const upgradeContext: UpgradeContext = (oldStates, newStates, oldContext) => {
        // oldStates is an array of state paths from the old version of the machine.
        // (e.g. [["a", "b"], ["a", "c"]] if "a" is a parallel state and is in both "b" and "c").
        // newStates is an array of state paths from the new version of the machine.
        // oldContext is the context associated with oldStates in the old version of the machine.

        return {
          ...oldContext,
          upgradeCount: oldContext.upgradeCount + 1
        };
      };
      ```
  - name: Machine instances
    description: |
      # Machine instance operations.
      
      Machine instances are instances of a machine definition.

      If you have a machine definition that controls a user onboarding flow,
      you would want a machine instance for each user.

      If you have a machine definition that controls access to a collaborative
      document, you would want a machine instance for each document.

      Machine instances have names that are unique within a machine definition.

      You can send events to machine instances to trigger transitions and can
      read the state of an instance.

      ## Consistency guarantees

      Processing for a machine instance is coordinated such that there is
      a single, linearizable history of events and state transitions.

      ## Limits

      Machine context (represented as JSON) may not exceed 400kb.
  - name: Logs
    description: |
      # Logs produced while processing transitions and migrations.

      State Backed collects any logs you emit while processing
      transitions and migrations and makes them available via this
      endpoint.

      State Backed also emits some logs of its own to provide context.

      We *highly* recommend logging structured JSON objects.
  - name: Realtime
    description: |
      # Realtime (websocket) endpoints

      State Backed allows you to subscribe to machine instance updates
      via websockets.
  - name: Tokens
    description: |
      # Endpoints for retrieving State Backed authorization tokens

      All calls to State Backed must include a JWT signed by one of your
      State Backed keys in the authorization header.

      The token should include an `act` claim that contains claims about your end user,
      which will be passed into your machine authorization functions (`allowRead` and `allowWrite`)
      as `authContext`. This allows you to, for instance, ensure that users can only send events
      to their own machine instances or instances that your application logic permits.

      These tokens are easily created by the [@statebacked/token](https://www.npmjs.com/package/@statebacked/token)
      library.

      However, the signing keys to create these tokens **must always** be kept secret and cannot
      be included in client-side applications.

      To allow you to use any authentication provider you want and to use State Backed without
      any server-side code, you can use our token exchange endpoints to securely exchange
      a JWT from your authentication provider for a State Backed JWT with the appropriate user claims.

      After configuring trusted identity providers and token providers, you will be able to
      exchange a JWT from any of your trusted identity providers for a token with claims and a signature
      generated by any of your token providers by posting to the /tokens endpoint.

      First, configure your trusted identity providers by posting to /idps.
      You will have to specify the audience and/or issuer that identifies a token from this IDP as well
      as the JWKS url where State Backed can retrieve the appropriate verification keys or
      the secret key that State Backed can use to verify the token (keys are stored encrypted in the
      State Backed vault).
      You will also provide a mapping, which extracts claims from the identity provider token
      to make them available to token providers.

      Then, configure your token providers by posting to /token-providers.
      You will give your token provider a service name to identify it (you might want a different
      service for each app you build, for instance) and a mapping that specifies the
      claims that should be included in any token generated by that token provider.

      After that, you have completely secure, end-to-end authenticated user sessions available
      in your State Backed backend without any server-side presence.

      ## Mappings

      Mappings are JSON objects whose structure matches the desired output of the mapping and whose
      values can refer to items from the input.

      A mapping of:

      ```javascript
      {
        "sub.$": "$.sub",
        "email.$": "$.email",
        "service": "my-service",
        "special": {
          "role.$": "$.role.id"
        }
      }
      ```

      With input of:

      ```javascript
      {
        "sub": "my-user-id",
        "email": "my-email@statebacked.dev",
        "role": {
          "id": "my-role"
        }
      }
      ```

      Will produce a result of:

      ```javascript
      {
        "sub": "my-user-id", // mapping keys that end in ".$" treat values as JSONPath expressions into the input
        "email": "my-email@statebacked.dev",
        "service": "my-service", // mapping keys that don't end in ".$" treat values as constants (unless the value is a mapping)
        "special": {
          "role": "my-role" // mappings are resolved recursively
        }
      }
      ```
  - name: Orgs
    description: Manage organizations
  - name: Billing
    description: Manage billing
  - name: Keys
    description: Manage signing keys

paths:
  /machines:
    get:
      tags:
        - Machines
      summary: List your machines
      security:
        - BearerAuth:
          - "machines.read"
    post:
      summary: Create a new machine definition.
      tags:
        - Machines
      security:
        - BearerAuth:
          - "machines.write"
      description: |
        Note: No instances of a machine definition can be created until
        you create a machine definition version for it.
  /machines/{machineSlug}:
    get:
      tags:
        - Machines
      summary: Get a machine definition.
      description: |
        Retrieve the machine definition
      security:
        - BearerAuth:
          - "machines.read"
    post:
      tags:
        - Machine instances
      summary: Create a new machine instance.
      description: |
        Create a new instance of the machine definition with the given slug.

        The `allowWrite` function for the machine definition version will be called
        to authorize the initial transition and, if it fails, a 403 with code
        `rejected-by-machine-authorizer` will be returned.

        Otherwise, the state of the machine instance after the initial transition
        will be returned.

        All top-level events have a 10 second timeout for the machine to settle.
        Settling means that the machine has reached a stable state and has no
        child services running.

        If the machine does not settle within 10 seconds but has completed at least
        one transition successfully, a 200 with the current state will be returned,
        the child services will be stopped, and error events will be delivered for
        each stopped service before the next event is sent.

        If a machine instance for this (`machineSlug`, instance `slug`) already exists,
        a 409 will be returned.
      security:
        - BearerAuth:
          - "instances.write"
    delete:
      tags:
        - Machines
      summary: Delete a machine and any versions and migrations associated with it.
      description: |
        Delete a machine and any versions and migrations associated with it.

        *THIS IS OBVIOUSLY A DANGEROUS OPERATION AND WILL INTENTIONALLY CAUSE DATA LOSS*

        If any instances exist for the machine, a 409 error will be returned with an `invalid-state` code.
        You can delete the instances and then retry the machine deletion.

        All versions associated with the machine and all migrations between those versions
        will be deleted.
        
        There is no option to recover data after a machine is deleted.

        To prevent accidental deletion, we require two validation parameters:
          - hmacSha256OfMachineNameWithMachineNameKey - `base64urlEncode(hmacSha256(key = "machine name", "machine name"))`
          - dangerDataWillBeDeletedForever - true

        A 400 error with the `parameter` set to the name of the incorrect parameter will be returned
        if the validation parameters are incorrect.

        This endpoint requires admin access.
      security:
        - BearerAuth:
          - "machines.admin"
  /machines/{machineSlug}/i:
    get:
      tags:
        - Machine instances
      summary: List the instances of this machine
      security:
        - BearerAuth:
          - "instances.read"
  /machines/{machineSlug}/i/{instanceSlug}:
    get:
      tags:
        - Machine instances
      summary: Get the current state of a machine instance.
      description: |
        Retrieve the state of the machine instance that was previously created by
        calling `POST /machines/{machineSlug}` and may have had events sent to it
        by calling `POST /machines/{machineSlug}/i/{instanceSlug}/events`.

        The `allowRead` function for the machine definition version will be called
        to authorize the read and, if it fails, a 403 with code
        `rejected-by-machine-authorizer` will be returned.

        Otherwise, the current state of the machine instance will be returned.

        Obviously, the state returned may be out of date by the time it is returned
        because reads are non-blocking but a the returned state will always be
        self-consistent.
      security:
        - BearerAuth:
          - "state.read"
    delete:
      tags:
        - Machine instances
      summary: Delete a machine instance and any transitions, state, or pending upgrades associated with it.
      description: |
        Delete a machine instance and any transitions, state, or pending upgrades associated with it.

        *THIS IS OBVIOUSLY A DANGEROUS OPERATION AND WILL INTENTIONALLY CAUSE DATA LOSS*

        All historical transitions associated with the machine and all current state and context
        will be deleted.
        
        There is no option to recover data after an instance is deleted.

        To prevent accidental deletion, we require two validation parameters:
          - hmacSha256OfMachineInstanceNameWithMachineNameKey - `base64urlEncode(hmacSha256(key = "machine name", "machine instance name"))`
          - dangerDataWillBeDeletedForever - true

        A 400 error with the `parameter` set to the name of the incorrect parameter will be returned
        if the validation parameters are incorrect.

        This endpoint requires admin access.
      security:
        - BearerAuth:
          - "instances.admin"
  /machines/{machineSlug}/i/{instanceSlug}/admin:
    get:
      tags:
        - Machine instances
      summary: Get the administrative state of an instance
      description: |
        Retrieve the state of the machine instance that was previously created by
        calling `POST /machines/{machineSlug}` and may have had events sent to it
        by calling `POST /machines/{machineSlug}/i/{instanceSlug}/events`.

        No machine authorizers will be called to authorize this read so this requires
        instances.read scope.

        The full context for the instance (instead of only public context) will be returned.
      security:
        - BearerAuth:
          - "instances.read"
  /machines/{machineSlug}/i/{instanceSlug}/events:
    get:
      tags:
        - Machine instances
      summary: List the transitions for this machine instance
      security:
        - BearerAuth:
          - "instances.admin"
    post:
      tags:
        - Machine instances
      summary: Send an event to a machine instance.
      description: |
        Send an event to the machine instance that was previously created by
        calling `POST /machines/{machineSlug}`.

        The `allowWrite` function for the machine definition version will be called
        to authorize the send and, if it fails, a 403 with code
        `rejected-by-machine-authorizer` will be returned.

        Otherwise, the state of the machine instance after any transitions resulting
        from the event will be returned.

        The request will wait for the machine to settle before returning a response.
        Settling means that the machine has reached a stable state and has no
        child services running.

        All top-level events have a 10 second timeout for the machine to settle.

        If the machine does not settle within 10 seconds but has completed at least
        one transition successfully, a 200 with the current state will be returned,
        the child services will be stopped, and error events will be delivered for
        each stopped service before the next event is sent.
      security:
        - BearerAuth:
          - "instances.write"
  /machines/{machineSlug}/i/{instanceSlug}/v:
    put:
      tags:
        - Machine instances
      summary: Update the desired machine version for an existing instance.
      description: |
        Set the desired machine version for an existing instance.

        The instance will not be upgraded immediately but will be upgraded
        the next time an event is sent to it from a settled state.

        A 400 with code "no-migration-path" will be returned if there is
        no path through the set of existing migrations from the current
        instance version to the desired instance version.
      security:
        - BearerAuth:
          - "instances.write"
  /machines/{machineSlug}/i/{instanceSlug}/status:
    put:
      tags:
        - Machine instances
      summary: Update the status of a machine instance
      description: |
        Set the status of the machine.

        Machines in the 'paused' status will reject any events sent to them
        with a 409 error with a code of "invalid-state".

        'running' instances will accept events normally.

        It is **dangerous** to set an instance's status to 'paused'!
        You will drop events and, because delayed events are only retried
        5 times (with ~30 seconds between each try), some delayed events
        may be dropped and **never** sent to your machine.

        This exists **purely** to stop a runaway machine instance that is
        stuck in a loop of creating too many events.

        This endpoint requires admin access.
      security:
        - BearerAuth:
          - "instances.admin"
  /machines/{machineSlug}/v:
    get:
      tags:
        - Machine versions
      summary: List the machine versions for this machine
      security:
        - BearerAuth:
          - "machine-versions.read"
    post:
      tags:
        - Machine versions
      summary: Provisionally create a new machine definition version.
      description: |
        This operation returns a code upload URL and fields that can be used
        to upload the code for the machine definition version.

        Once the code is uploaded, call `PUT /machines/:machineSlug/v/:machineDefinitionVersionId`
        with the `machineDefinitionVersionId` returned from this operation to
        finalize the creation of the machine definition version.
      security:
        - BearerAuth:
          - "machine-versions.write"
  /machines/{machineSlug}/v/{signedMachineVersionId}:
    put:
      tags:
        - Machine versions
      summary: Finalize creation of a machine definition version.
      description: |
        After retrieving the `machineDefinitionVersionId` and code upload
        instructions from `POST /machines/:machineSlug/v`, and after
        uploading the code as described, call this operation to finalize
        the creation of the machine definition version.

        After this operation, you can create instances of the machine
        definition with  this version.
      security:
        - BearerAuth:
          - "machine-versions.write"
  /machines/{machineSlug}/migrations:
    post:
      tags:
        - Machine version migrations
      summary: Provisionally create a new machine version migration.
      description: |
        This operation returns a code upload URL and fields that can be used
        to upload the code for the machine version migration.

        Once the code is uploaded, call `PUT /machines/:machineSlug/migrations/:machineVersionMigrationId`
        with the `machineVersionMigrationId` returned from this operation to
        finalize the creation of the machine version migration.
      security:
        - BearerAuth:
          - "machine-versions.write"
  /machines/{machineSlug}/migrations/{signedMachineVersionMigrationId}:
    put:
      tags:
        - Machine version migrations
      summary: Finalize creation of a machine version migration.
      description: |
        After retrieving the `machineVersionMigrationId` and code upload
        instructions from `POST /machines/:machineSlug/migrations`, and after
        uploading the code as described, call this operation to finalize
        the creation of the machine version migration.

        After this operation, you can upgrade existing machine instances
        using this migration.
      security:
        - BearerAuth:
          - "machine-versions.write"
  /logs:
    get:
      tags:
        - Logs
      summary: Retrieve logs for a time range.
      description: |
        Retrieve logs starting at the `from` time, optionally
        filtered by `to`, `machine`, `instance`, and `version`.

        You will receive at most 100 log entries (each consisting
        of potentially multiple lines) but you may receive fewer
        entries due to various partitioning schemes.

        You may retry the call by specifying the returned `maxTimestamp`
        as the new `from` time to retrieve additional logs.
      security:
        - BearerAuth:
          - "logs.read"
  /rt:
    get:
      tags:
        - Realtime
      summary: Subscribe to real-time updates of machine instances.
      description: |
        This is a websocket endpoint.
        Connect and send WSToServerMsg messages and receive WSToClientMsg messages.
  /idps:
    get:
      tags:
        - Tokens
      summary: List the identity providers configured for your org
      security:
        - BearerAuth:
          - "tokens.admin"
    post:
      tags:
        - Tokens
      summary: Upsert an identity provider
      description: |
        Token exchange involves exchanging an identity provider-signed token for a
        State Backed-signed token. By adding an identity provider configuration to
        State Backed, you are instructing State Backed to trust any valid token
        from that identity provider when evaluating whether to allow a token exchange.
        You are also extracting the claims from that token that you want to make available
        to your token providers to include in the State Backed token.

        For example, if you are using Auth0 as your identity provider, you can configure
        State Backed to trust your Auth0 tokens by calling:

        ```bash
        curl -XPOST https://statebacked.dev/idps \
          -H 'authorization: Bearer sbsk_...'
          --data '{
            "aud": "https://<your-auth0-domain>.us.auth0.com/api/v2/",
            "iss": "https://<your-auth0-domain>.us.auth0.com/",
            "jwksUrl": "https://<your-auth0-domain>.us.auth0.com/.well-known/jwks.json",
            "algs": ["RS256"],
            "mapping": {
              "sub.$": "$.sub",
              "email.$": "$.email",
              "provider": "auth0"
            }
          }'
        ```

        State Backed uses the audience (`aud`) and issuer (`iss`) claims in any tokens
        provided for exchange to identify the identity provider to use for verification.

        In this example, token providers would be have access to `sub`, `email`, and `provider`
        claims that they could include in the resultant State Backed token.

        Upserts may change algorithms, mappings, keys or jwksUrls.

        This endpoint requires admin access.
      security:
        - BearerAuth:
          - "tokens.admin"
    delete:
      tags:
        - Tokens
      summary: Delete an identity provider
      description: |
        Delete the identity provider and immediately reject any token exchange
        requests that provide tokens signed by the idp.
      security:
        - BearerAuth:
          - "tokens.admin"
  /token-providers:
    get:
      tags:
        - Tokens
      summary: List the token providers configured for your org
      security:
        - BearerAuth:
          - "tokens.admin"
    post:
      tags:
        - Tokens
      summary: Upsert a token provider
      description: |
        Token exchange involves exchanging an identity provider-signed token for a
        State Backed-signed token. 

        Token providers are responsible for creating State Backed tokens from a standardized
        claim set extracted from identity provider tokens by their mappings.

        Token providers are identified by a service name.
        You might, for instance, want a service name for each application that you host
        with State Backed.

        Token providers also specify the State Backed key to use to sign the tokens they
        generate and a mapping that creates the claims for the generated token.

        For example, if your identity provider mappings extract claims like this:

        ```
        {
          "sub": "your-sub",
          "email": "your-email",
          "provider": "identity-provider"
        }
        ```

        you could create a token provider like this:

        ```bash
        curl -XPOST https://statebacked.dev/token-providers \
          -H 'authorization: Bearer sbsk_...'
          --data '{
            "keyId": "sbk_...", // ID for a previously-created State Backed key
            "service": "your-app", // any identifier for your token provider
            "mapping": {
              "sub.$": "$.sub",
              "email.$": "$.email",
              "provider.$": "$.provider"
            }
          }'
        ```

        That token provider would allow you to exchange any of your identity provider-
        signed tokens for a State Backed token that includes the sub, email, and provider
        claims, all of which would be available for your use in `allowRead` and `allowWrite`
        functions in your machine definitions.

        Upserts may change key ids and mappings.

        This endpoint requires admin access.
      security:
        - BearerAuth:
          - "tokens.admin"
  /token-providers/{service}:
    delete:
      tags:
        - Tokens
      summary: Delete a token provider
      description: |
        Delete the token provider and immediately reject any token exchange
        requests that request tokens using the token provider's service.
      security:
        - BearerAuth:
          - "tokens.admin"
  /tokens:
    post:
      tags:
        - Tokens
      summary: Exchange an identity provider-signed token for a State Backed token
      description: |
        Once you have configured at least one identity provider (by posting to /idps)
        and at least one token provider (by posting to /token-providers), you can exchange
        any identity provider token for a token generated by one of your token providers.

        This allows you to have completely secure, end-to-end authorization with your
        State Backed machine instances without any server-side code while using your
        identity provider of choice.

        This endpoint should generally conform to https://datatracker.ietf.org/doc/html/rfc8693
  /orgs:
    get:
      tags:
        - Orgs 
      summary: List your organizations
      security:
        - BearerAuth:
          - "org.read"
  /keys:
    get:
      tags:
        - Keys
      summary: List your keys
      security:
        - BearerAuth:
          - "tokens.admin"
  /billing:
    get:
      tags:
        - Billing
      summary: Retrieve the link to your organization's billing portal
      security:
        - BearerAuth:
          - "org.write"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
